# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: RestoreBuildNTest

pool:
  vmImage: 'windows-2019'

  steps:

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
    displayName: 'dotnet restore all'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
    displayName: 'dotnet build all'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      projects: '**/*tests*.csproj'
    displayName: 'dotnet test all'